---
- hosts: all
  tasks:
  - name: format and resize filesystem
    filesystem:
      dev: "/dev/disk/by-id/scsi-0HC_Volume_{{ disk_id }}"
      fstype: xfs
      resizefs: yes
  - name: mount home drive
    mount:
      path: /home
      src: "/dev/disk/by-id/scsi-0HC_Volume_{{ disk_id }}"
      fstype: xfs
      state: mounted
...
