---
- hosts: all
  tasks:
  - name: configure network
    include_role:
      name: linux-system-roles.network
    vars:
      network_provider: nm
      network_connections:
      - name: eth0
        state: up
        type: ethernet
        interface_name: eth0
        ip:
          gateway4: "{{ gateway4 }}"
          address: "{{ ips }}"
          dns: "{{ nameservers }}"
          dns_search:
          - "{{ domain_name }}"
          route:
          - network: "{{ gateway4 }}"
            prefix: "32"
  - name: define hostname
    hostname:
      name: "{{ server_name }}.{{ domain_name }}"
...
